### ISSUE TITLE
Action fails on Linux

### ISSUE THREAD

**Issue by vadi2** [OrbitalOwen/github-actions-screenshot#2]
I install imagemagick, but the action still fails:

```
(node:11288) UnhandledPromiseRejectionWarning: Error: Command failed: xrandr
Can't open display 
```

(https://github.com/Mudlet/Mudlet/runs/682749578?check_suite_focus=true)

Any ideas?

**Comment by OrbitalOwen** [comment]
Hi @vadi2 - Sorry to take so long to get back to you on this, I must have missed this notification!

The screenshot behavior is handled by [screenshot-desktop](https://github.com/bencevans/screenshot-desktop), all this action does is call the screenshot function and upload it as an artifact. If this is something you still need, you'll probably get more useful support there.
